# Generated by Django 4.2.9 on 2024-01-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client_filter_operator_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='client_filter_tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
