# Generated by Django 4.2.9 on 2024-01-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='count_success_sent_messages',
            field=models.IntegerField(default=0),
        ),
    ]
