#!/bin/bash

read -rp "DEBUG: [True]" DEBUG
DEBUG=${DEBUG:-True}
read -rp "CELERY_BROKER_URL: [redis://localhost:6379/0]" CELERY_BROKER_URL
CELERY_BROKER_URL=${CELERY_BROKER_URL:-'redis://localhost:6379/0'}
read -rp "CELERY_RESULT_BACKEND: [redis://localhost:6379/1]" CELERY_RESULT_BACKEND
CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-'redis://localhost:6379/1'}
read -rp "CELERY_CACHE_BACKEND: [django-db]" CELERY_CACHE_BACKEND
CELERY_CACHE_BACKEND=${CELERY_CACHE_BACKEND:-'django-db'}
read -rp "JWT_AUTH_TOKEN FOR https://probe.fbrq.cloud/v1: " JWT_AUTH_TOKEN

env_file="../notification_server/.env"
echo $CELERY_BROKER_URL
cat << EOF >$env_file

DEBUG=$DEBUG
CELERY_BROKER_URL=$CELERY_BROKER_URL
CELERY_RESULT_BACKEND=$CELERY_RESULT_BACKEND
CELERY_CACHE_BACKEND=$CELERY_CACHE_BACKEND
JWT_AUTH_TOKEN=$JWT_AUTH_TOKEN
EOF

